export const brStates = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];

export const areasDeAtuacao = [
  "Serviços de Eletrodomésticos",
  "Assistência Técnica de Informática",
  "Manutenção de Dispositivos Móveis",
  "Reparos Industriais",
  "Serviços de Áudio e Vídeo",
  "Manutenção de Redes e TI",
  "Refrigeração e Climatização",
  "Assistência Técnica de Impressão",
  "Serviços Gerais de Refrigeração",
  "Reparos em Equipamentos de Saúde",
  "Serviços de Lavanderia",
  "Assistência Técnica de Cozinha",
  "Serviços Elétricos",
  "Manutenção de Ferramentas",
  "Assistência Técnica de Jogos",
  "Serviços de Jardinagem",
  "Reformas e Construção",
  "Manutenção de Equipamentos Esportivos",
  "Serviços de Telecomunicações",
  "Manutenção de Infraestrutura",
  "Reformas Residenciais",
  "Serviços de Fotografia",
  "Sistemas de Segurança",
  "Manutenção de Laboratórios",
  "Serviços Agrícolas",
  "Assistência Técnica de Costura",
  "Serviços Hidráulicos",
  "Manutenção de Iluminação",
  "Serviços de Solda",
  "Manutenção de Piscinas",
];
