import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "next-themes";
import Floating from "@/components/floating";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`relative`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          // enableSystem
          disableTransitionOnChange
        >
          <Toaster className="" />
          {children}
          <Floating />{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
